# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89ab792fa2cfc545b0a0989d053e73980b1c3e2fc8c6059f21200fbbf00afd69fafd9c6179ad70061fbe1da987f6f7c5d0c6d968be7a8509162729e25235420
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID_DEV"]%>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET_DEV"]%>

test:
  secret_key_base: 828522d9dae1294593ad1c6d62e1850b72800dca71d0c1c14ec70c8150e07bd8cd8ddcc2a9ad55f15905f771e41507f14f7907e44b493efd7839427de3b30dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
